version: 2

sphinx:
  builder: html
  configuration: h3ronpy/docs/source/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.13"

  jobs:
    pre_create_environment:
      # install rust manually. https://github.com/readthedocs/readthedocs.org/issues/11488
      - asdf install rust 1.91
      - asdf global rust 1.91

python:
  install:
    - requirements: h3ronpy/docs/requirements.txt
    - method: pip
      path: ./h3ronpy
