version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
    rust: "1.64"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
